name: PHPCS

on:
  push:
    branches: [ main, chore/**, feature/**, fix/** ]
  pull_request:
    branches: [ main ]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress --prefer-dist
      - name: Show PHPCS version
        run: vendor/bin/phpcs --version
      - name: Run PHPCS (WordPress standards)
        run: vendor/bin/phpcs --standard=phpcs.xml.dist
